apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    {{- include "larpit.labels" . | nindent 4 }}
    component: node
spec:
  selector:
    stack: larpit
    component: node
  ports:
    - port: 3000
      targetPort: 3000
